import type { Service } from './types';

export const SERVICES: Service[] = [
  {
    id: 'oil',
    slug: 'zamena-masla',
    title: 'Замена масла и фильтров',
    description: 'Масло по каталогу вашего авто.',
    priceFrom: 15,
    priceTo: 20,
    popular: true,
    photo: '/services/oil.webp',
  },
  {
    id: 'diagnostics',
    slug: 'diagnostika',
    title: 'Компьютерная диагностика',
    description: 'Находим причину, а не продаём лишнее',
    priceFrom: 10,
    popular: true,
    photo: '/services/diag.webp',
  },
  {
    id: 'suspension',
    slug: 'diagnostika-podveski',
    title: 'Диагностика подвески',
    description: 'На подъёмнике, с показом каждого узла. Первым 20 — бесплатно.',
    priceFrom: 0,
    photo: '/services/diag.webp',
  },
  {
    id: 'timing',
    slug: 'remen-grm',
    title: 'Замена ремня ГРМ',
    description: 'По регламенту, с роликами и помпой.',
    priceFrom: 80,
    priceTo: 150,
    photo: '/services/engine.webp',
  },
  {
    id: 'clutch',
    slug: 'sceplenie',
    title: 'Замена сцепления',
    description: 'Комплект под ваш пробег и стиль.',
    priceFrom: 70,
    priceTo: 180,
    photo: '/services/clutch.webp',
  },
  {
    id: 'brakes',
    slug: 'kolodki',
    title: 'Замена колодок и дисков',
    description: 'Покажем износ — решаете вы.',
    priceFrom: 15,
    photo: '/services/brakes.webp',
  },
  {
    id: 'alignment',
    slug: 'razval-shozdenie',
    title: 'Развал-схождение',
    description: '3D-стенд, распечатка до/после.',
    priceFrom: 20,
    photo: '/services/align.webp',
  },
  {
    id: 'tyres',
    slug: 'shinomontazh',
    title: 'Шиномонтаж',
    description: 'Смена, проколы, хранение.',
    priceFrom: 6,
    unit: 'за колесо',
    photo: '/services/tyres.webp',
  },
  {
    id: 'ac',
    slug: 'kondicioner',
    title: 'Заправка и ремонт кондиционера',
    description: 'Ищем утечку, а не заливаем.',
    priceFrom: 100,
    photo: '/services/ac.webp',
  },
];
